/* FRONTEND ONLY. Replace demoJSON with data received from your ESP8266/server. */
const demoJSON = { device_id: "COLD_STORAGE_01", temperature: 14.2, humidity: 76, status: "SAFE", cooling: "ON", timestamp: new Date().toISOString() };
const history = [{ time: "08:00", temperature: 13.2 }, { time: "10:00", temperature: 13.8 }, { time: "12:00", temperature: 14.0 }, { time: "14:00", temperature: 14.2 }, { time: "16:00", temperature: 14.0 }, { time: "18:00", temperature: 14.2 }];



const $ = id => document.getElementById(id);
function formatTime(ts) { const d = new Date(ts); return Number.isNaN(d.getTime()) ? "--" : d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }
function updateDashboard(data) { const t = Number(data.temperature), h = Number(data.humidity), status = String(data.status || "UNKNOWN").toUpperCase(), cooling = String(data.cooling || "UNKNOWN").toUpperCase(); $("deviceId").textContent = data.device_id || "COLD_STORAGE_01"; $("temperature").textContent = Number.isFinite(t) ? t.toFixed(1) : "--"; $("temperatureSmall").textContent = Number.isFinite(t) ? t.toFixed(1) : "--"; $("humidity").textContent = Number.isFinite(h) ? h.toFixed(0) : "--"; $("humiditySmall").textContent = Number.isFinite(h) ? h.toFixed(0) : "--"; $("storageStatus").textContent = status; $("statusSmall").textContent = status; $("coolingState").textContent = cooling; $("coolingSmall").textContent = cooling; $("lastUpdated").textContent = formatTime(data.timestamp); const warning = status === "WARNING" || (Number.isFinite(t) && t >= 18); const banner = $("alertBanner"); banner.classList.toggle("warning", warning); banner.classList.toggle("safe", !warning); $("alertIcon").textContent = warning ? "!" : "✓"; $("alertTitle").textContent = warning ? "Attention: storage needs checking" : "Storage condition is safe"; $("alertMessage").textContent = warning ? "The temperature is above the configured warning level." : "The monitored conditions are within the configured range."; $("jsonPreview").textContent = JSON.stringify(data, null, 2) }
function setConnection(connected) { $("connectionText").textContent = connected ? "Connected" : "Connection unavailable"; $("connectionDot").classList.toggle("offline", !connected);["sensorState", "controllerState", "wifiState", "serverState"].forEach(id => { const e = $(id); e.textContent = connected ? "Online" : "Offline"; e.classList.toggle("good", connected); e.classList.toggle("bad", !connected) }) }
function drawChart(points) { const canvas = $("temperatureChart"), rect = canvas.getBoundingClientRect(), dpr = devicePixelRatio || 1; canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; const ctx = canvas.getContext("2d"); ctx.scale(dpr, dpr); const w = rect.width, h = rect.height, p = { left: 48, right: 18, top: 20, bottom: 34 }, cw = w - p.left - p.right, ch = h - p.top - p.bottom, vals = points.map(x => x.temperature), min = Math.floor(Math.min(...vals) - 1), max = Math.ceil(Math.max(...vals) + 1); ctx.clearRect(0, 0, w, h); ctx.strokeStyle = "#dbe6ec"; ctx.lineWidth = 1; ctx.fillStyle = "#617486"; ctx.font = "11px Arial"; for (let i = 0; i <= 4; i++) { const y = p.top + ch * i / 4, v = max - (max - min) * i / 4; ctx.beginPath(); ctx.moveTo(p.left, y); ctx.lineTo(w - p.right, y); ctx.stroke(); ctx.fillText(`${v.toFixed(0)}°`, 10, y + 4) } points.forEach((pt, i) => { const x = p.left + cw * i / Math.max(points.length - 1, 1); ctx.fillText(pt.time, x - 13, h - 12) }); const xy = points.map((pt, i) => ({ x: p.left + cw * i / Math.max(points.length - 1, 1), y: p.top + ch - ((pt.temperature - min) / (max - min)) * ch })); ctx.beginPath(); xy.forEach((pt, i) => i ? ctx.lineTo(pt.x, pt.y) : ctx.moveTo(pt.x, pt.y)); ctx.strokeStyle = "#1769aa"; ctx.lineWidth = 3; ctx.lineJoin = "round"; ctx.lineCap = "round"; ctx.stroke(); xy.forEach(pt => { ctx.beginPath(); ctx.arc(pt.x, pt.y, 4, 0, Math.PI * 2); ctx.fillStyle = "#1769aa"; ctx.fill() }) }
function simulateRefresh() { const next = { ...demoJSON, temperature: +(demoJSON.temperature + (Math.random() * .8 - .4)).toFixed(1), humidity: Math.max(0, Math.min(100, Math.round(demoJSON.humidity + (Math.random() * 4 - 2)))), timestamp: new Date().toISOString() }; next.status = next.temperature >= 18 ? "WARNING" : next.temperature >= 15 ? "COOLING" : "SAFE"; next.cooling = next.temperature >= 15 ? "ON" : "OFF"; Object.assign(demoJSON, next); history.push({ time: formatTime(next.timestamp), temperature: next.temperature }); if (history.length > 8) history.shift(); updateDashboard(demoJSON); drawChart(history) }
$("refreshBtn").addEventListener("click", simulateRefresh); window.addEventListener("resize", () => drawChart(history)); updateDashboard(demoJSON); setConnection(true); drawChart(history);
/* Future integration example:
fetch("/api/cold-storage/COLD_STORAGE_01").then(r=>r.json()).then(data=>{updateDashboard(data);setConnection(true)}).catch(()=>setConnection(false));
*/
